# This file contains values from Cookiecutter

default_context:
  project_name: "fractaldna"
  project_description: "Awesome `fractaldna` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "fractaldna"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "fractaldna"
  email: "hello@fractaldna.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
