name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: apt-get install -y pandoc && python -m pip install -r requirements-dev.txt
